"""
Regenerate database/seed.sql from the current `places` table.

Run this after enrich_places.py so the committed seed reflects the enriched data
and teammates get it through the normal seed path (no API keys, no re-fetching).

Usage (from backend/, venv active):
    python scripts/dump_seed.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.db.session import SessionLocal
from app.models.place import Place

SEED_PATH = Path(__file__).resolve().parents[2] / "database" / "seed.sql"

COLUMNS = [
    "name_en", "name_pl", "category", "description", "opening_hours", "duration",
    "price_range", "image_url", "latitude", "longitude",
    "address", "website", "osm_id", "wikipedia_title", "image_attribution", "source",
]


def sql_value(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def main():
    db = SessionLocal()
    try:
        places = db.query(Place).order_by(Place.id).all()
        rows = []
        for p in places:
            values = ", ".join(sql_value(getattr(p, col)) for col in COLUMNS)
            rows.append(f"({values})")

        body = ",\n".join(rows)
        sql = (
            "-- Generated by scripts/dump_seed.py — do not edit by hand.\n"
            "-- Source: places table after OSM + Wikipedia enrichment.\n"
            "-- Attribution: place data © OpenStreetMap contributors (ODbL);\n"
            "-- images & descriptions via Wikipedia/Wikimedia Commons (see image_attribution).\n\n"
            f"INSERT INTO places ({', '.join(COLUMNS)}) VALUES\n{body};\n"
        )
        SEED_PATH.write_text(sql, encoding="utf-8")
        print(f"Wrote {len(places)} rows to {SEED_PATH}")
    finally:
        db.close()


if __name__ == "__main__":
    main()
